[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
clap = { version ="4.0.23", features = ["derive"] }
md5 = "0.7.0"
itertools = "0.10.5"
